version: '2'
services:
  neo4j:
    image: neo4j
    ports:
     - "7474:7474"
     - "7687:7687"
    environment:
     - NEO4J_dbms_memory_heap_initial__size=1G
     - NEO4J_dbms_memory_heap_max__size=3G
    volumes:
     - "$HOME/neo4j/data:/data"
     - "../dataset:/var/lib/neo4j/import"
  server:
    image: webserver
    ports:
     - "8080:8080"
    volumes:
     - "../app:/app"
    entrypoint:
     - python3
     - /app/app.py
